version: '3.3'
services:
    csvserver:
        volumes:
            - '/root/csvserver/inputFile:/csvserver/inputdata'
        environment:
            - CSVSERVER_BORDER=orange
        ports:
            - '9393:9300'
        image: 'infracloudio/csvserver:latest'
